./repos/OXIDE
/RESULT/TRAIN_VAL_LOG/BERT_0607_each
Traceback (most recent call last):
  File "./repos/OXIDE/train_each.py", line 486, in <module>
    main(args)
  File "./repos/OXIDE/train_each.py", line 100, in main
    os.makedirs(path, exist_ok=True)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/RESULT'
./repos/OXIDE
/RESULT/TRAIN_VAL_LOG/BERT_0607_each
Traceback (most recent call last):
  File "./repos/OXIDE/train_each.py", line 486, in <module>
    main(args)
  File "./repos/OXIDE/train_each.py", line 100, in main
    os.makedirs(path, exist_ok=True)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/RESULT'
./repos/OXIDE
/RESULT/TRAIN_VAL_LOG/BERT_0607_each
Traceback (most recent call last):
  File "./repos/OXIDE/train_each.py", line 486, in <module>
    main(args)
  File "./repos/OXIDE/train_each.py", line 100, in main
    os.makedirs(path, exist_ok=True)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/RESULT'
./repos/OXIDE
/RESULT/TRAIN_VAL_LOG/BERT_0607_each
Traceback (most recent call last):
  File "./repos/OXIDE/train_each.py", line 486, in <module>
    main(args)
  File "./repos/OXIDE/train_each.py", line 100, in main
    os.makedirs(path, exist_ok=True)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/RESULT'
./repos/OXIDE
/RESULT/TRAIN_VAL_LOG/BERT_0607_each
Traceback (most recent call last):
  File "./repos/OXIDE/train_each.py", line 486, in <module>
    main(args)
  File "./repos/OXIDE/train_each.py", line 100, in main
    os.makedirs(path, exist_ok=True)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/RESULT'
./repos/OXIDE
/RESULT/TRAIN_VAL_LOG/BERT_0607_each
Traceback (most recent call last):
  File "./repos/OXIDE/train_each.py", line 486, in <module>
    main(args)
  File "./repos/OXIDE/train_each.py", line 100, in main
    os.makedirs(path, exist_ok=True)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/RESULT'
./repos/OXIDE
/RESULT/TRAIN_VAL_LOG/BERT_0607_each
Traceback (most recent call last):
  File "./repos/OXIDE/train_each.py", line 486, in <module>
    main(args)
  File "./repos/OXIDE/train_each.py", line 100, in main
    os.makedirs(path, exist_ok=True)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/RESULT'
./repos/OXIDE
/RESULT/TRAIN_VAL_LOG/BERT_0607_each
Traceback (most recent call last):
  File "./repos/OXIDE/train_each.py", line 486, in <module>
    main(args)
  File "./repos/OXIDE/train_each.py", line 100, in main
    os.makedirs(path, exist_ok=True)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/RESULT'
./repos/OXIDE
/RESULT/TRAIN_VAL_LOG/BERT_0607_each
Traceback (most recent call last):
  File "./repos/OXIDE/train_each.py", line 486, in <module>
    main(args)
  File "./repos/OXIDE/train_each.py", line 100, in main
    os.makedirs(path, exist_ok=True)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/RESULT'
./repos/OXIDE
/RESULT/TRAIN_VAL_LOG/BERT_0607_each
Traceback (most recent call last):
  File "./repos/OXIDE/train_each.py", line 486, in <module>
    main(args)
  File "./repos/OXIDE/train_each.py", line 100, in main
    os.makedirs(path, exist_ok=True)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/RESULT'
./repos/OXIDE
/RESULT/TRAIN_VAL_LOG/BERT_0607_each
Traceback (most recent call last):
  File "./repos/OXIDE/train_each.py", line 486, in <module>
    main(args)
  File "./repos/OXIDE/train_each.py", line 100, in main
    os.makedirs(path, exist_ok=True)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/RESULT'
./repos/OXIDE
/RESULT/TRAIN_VAL_LOG/BERT_0607_each
Traceback (most recent call last):
  File "./repos/OXIDE/train_each.py", line 486, in <module>
    main(args)
  File "./repos/OXIDE/train_each.py", line 100, in main
    os.makedirs(path, exist_ok=True)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/RESULT'
./repos/OXIDE
/RESULT/TRAIN_VAL_LOG/BERT_0607_each
Traceback (most recent call last):
  File "./repos/OXIDE/train_each.py", line 486, in <module>
    main(args)
  File "./repos/OXIDE/train_each.py", line 100, in main
    os.makedirs(path, exist_ok=True)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/RESULT'
./repos/OXIDE
/RESULT/TRAIN_VAL_LOG/BERT_0607_each
Traceback (most recent call last):
  File "./repos/OXIDE/train_each.py", line 486, in <module>
    main(args)
  File "./repos/OXIDE/train_each.py", line 100, in main
    os.makedirs(path, exist_ok=True)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/RESULT'
./repos/OXIDE
/RESULT/TRAIN_VAL_LOG/BERT_0607_each
Traceback (most recent call last):
  File "./repos/OXIDE/train_each.py", line 486, in <module>
    main(args)
  File "./repos/OXIDE/train_each.py", line 100, in main
    os.makedirs(path, exist_ok=True)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/RESULT'
./repos/OXIDE
/RESULT/TRAIN_VAL_LOG/BERT_0607_each
Traceback (most recent call last):
  File "./repos/OXIDE/train_each.py", line 486, in <module>
    main(args)
  File "./repos/OXIDE/train_each.py", line 100, in main
    os.makedirs(path, exist_ok=True)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/RESULT'
./repos/OXIDE
/RESULT/TRAIN_VAL_LOG/BERT_0607_each
Traceback (most recent call last):
  File "./repos/OXIDE/train_each.py", line 486, in <module>
    main(args)
  File "./repos/OXIDE/train_each.py", line 100, in main
    os.makedirs(path, exist_ok=True)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/RESULT'
./repos/OXIDE
/RESULT/TRAIN_VAL_LOG/BERT_0607_each
Traceback (most recent call last):
  File "./repos/OXIDE/train_each.py", line 486, in <module>
    main(args)
  File "./repos/OXIDE/train_each.py", line 100, in main
    os.makedirs(path, exist_ok=True)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/RESULT'
./repos/OXIDE
/RESULT/TRAIN_VAL_LOG/BERT_0607_each
Traceback (most recent call last):
  File "./repos/OXIDE/train_each.py", line 486, in <module>
    main(args)
  File "./repos/OXIDE/train_each.py", line 100, in main
    os.makedirs(path, exist_ok=True)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/RESULT'
./repos/OXIDE
/RESULT/TRAIN_VAL_LOG/BERT_0607_each
Traceback (most recent call last):
  File "./repos/OXIDE/train_each.py", line 486, in <module>
    main(args)
  File "./repos/OXIDE/train_each.py", line 100, in main
    os.makedirs(path, exist_ok=True)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/RESULT'
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at ./repos/BERTS/matbert-base-uncased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at ./repos/BERTS/matbert-base-uncased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/data/dydtkddhkdwk/anaconda3/envs/BERTRANKING/lib/python3.8/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "
./repos/OXIDE
./repos/OXIDE/RESULT/TRAIN_VAL_LOG/BERT_0607_each
./repos/OXIDE/RESULT/TRAIN_LOSS_AVG_IMAGE/BERT_0607_each
./repos/OXIDE/RESULT/VALIDATION_METRIC_IMAGE_NANOPARTICLE/BERT_0607_each
./repos/OXIDE/RESULT/VALIDATION_METRIC_IMAGE_MAIN_SUBJECT/BERT_0607_each
./repos/OXIDE/RESULT/VALIDATION_METRIC_IMAGE_AVG/BERT_0607_each
./repos/OXIDE/RESULT/TEST_METRIC_LOG/BERT_0607_each
./repos/OXIDE/RESULT/TEST_METRIC_IMAGE_NANOPARTICLE/BERT_0607_each
./repos/OXIDE/RESULT/TEST_METRIC_IMAGE_MAIN_SUBJECT/BERT_0607_each
./repos/OXIDE/RESULT/TEST_METRIC_IMAGE_AVG/BERT_0607_each
./repos/MODEL_WEIGHT/BERT_0607_each
  0%|          | 0/150 [00:00<?, ?it/s]
  0%|          | 0/30 [00:00<?, ?it/s][A
  3%|▎         | 1/30 [00:01<00:44,  1.53s/it][A
  7%|▋         | 2/30 [00:01<00:22,  1.24it/s][A
 10%|█         | 3/30 [00:02<00:15,  1.75it/s][A
 13%|█▎        | 4/30 [00:02<00:12,  2.16it/s][A
 17%|█▋        | 5/30 [00:02<00:10,  2.49it/s][A
 20%|██        | 6/30 [00:03<00:08,  2.74it/s][A
 23%|██▎       | 7/30 [00:03<00:07,  2.93it/s][A
 27%|██▋       | 8/30 [00:03<00:07,  3.06it/s][A
 30%|███       | 9/30 [00:03<00:06,  3.16it/s][A
 33%|███▎      | 10/30 [00:04<00:06,  3.23it/s][A
 37%|███▋      | 11/30 [00:04<00:05,  3.28it/s][A
 40%|████      | 12/30 [00:04<00:05,  3.32it/s][A
 43%|████▎     | 13/30 [00:05<00:05,  3.34it/s][A
 47%|████▋     | 14/30 [00:05<00:04,  3.36it/s][A
 50%|█████     | 15/30 [00:05<00:04,  3.37it/s][A
 53%|█████▎    | 16/30 [00:05<00:04,  3.38it/s][A
 57%|█████▋    | 17/30 [00:06<00:03,  3.39it/s][A
 60%|██████    | 18/30 [00:06<00:03,  3.39it/s][A
 63%|██████▎   | 19/30 [00:06<00:03,  3.39it/s][A
 67%|██████▋   | 20/30 [00:07<00:02,  3.39it/s][A
 70%|███████   | 21/30 [00:07<00:02,  3.39it/s][A
 73%|███████▎  | 22/30 [00:07<00:02,  3.39it/s][A
 77%|███████▋  | 23/30 [00:08<00:02,  3.39it/s][A
 80%|████████  | 24/30 [00:08<00:01,  3.40it/s][A
 83%|████████▎ | 25/30 [00:08<00:01,  3.40it/s][A
 87%|████████▋ | 26/30 [00:08<00:01,  3.40it/s][A
 90%|█████████ | 27/30 [00:09<00:00,  3.39it/s][A
 93%|█████████▎| 28/30 [00:09<00:00,  3.39it/s][A
 97%|█████████▋| 29/30 [00:09<00:00,  3.39it/s][A
100%|██████████| 30/30 [00:09<00:00,  3.77it/s][A100%|██████████| 30/30 [00:09<00:00,  3.01it/s]
  1%|          | 1/150 [00:13<32:27, 13.07s/it]Epoch 1/150, Train Loss Nanoparticle: 0.35470532178878783, Train Loss Main Subject: 0.4516549011071523
Validation Loss Nanoparticle: 0.298686258494854, Validation Loss Main Subject: 0.3356142044067383
Validation loss decreased (inf --> 0.298686).  Saving model ...
Validation loss decreased (inf --> 0.335614).  Saving model ...

  0%|          | 0/30 [00:00<?, ?it/s][A
  3%|▎         | 1/30 [00:00<00:08,  3.38it/s][A
  7%|▋         | 2/30 [00:00<00:08,  3.38it/s][A
 10%|█         | 3/30 [00:00<00:07,  3.40it/s][A
 13%|█▎        | 4/30 [00:01<00:07,  3.39it/s][A
 17%|█▋        | 5/30 [00:01<00:07,  3.39it/s][Aslurmstepd: error: *** JOB 47957 ON moana-y5 CANCELLED AT 2024-06-07T07:14:41 ***

 20%|██        | 6/30 [00:01<00:07,  3.39it/s][A